apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - grafana-alertrules.yaml
  - prometheus-rules.yaml
  - evidently-servicemonitor.yaml
  - model-server-servicemonitor.yaml
