apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: model-server-monitor
  namespace: monitoring
  labels:
    # Nhãn này cực kỳ quan trọng, nó phải khớp với tên Release của Prometheus (mặc định là 'monitoring' theo script của chúng ta)
    # Nếu thiếu nhãn này, Prometheus Operator sẽ bỏ qua (không nhặt file này)
    release: monitoring
spec:
  selector:
    matchLabels:
      # Tìm TẤT CẢ các Service có chứa nhãn này
      component: model-server
  namespaceSelector:
    matchNames:
      - default # Argo Workflow tạo model-server ở namespace default
  endpoints:
    - port: http # Phải khớp với name: http ở dòng 83 của file deploy-workflowtemplate.yaml
      path: /metrics
      interval: 15s
