"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values,
see https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_bool(name, default=False):
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


def env_list(name, default=""):
    value = os.environ.get(name, default)
    return [item.strip() for item in value.split(",") if item.strip()]


def env_list_first(names, default=""):
    for name in names:
        value = os.environ.get(name)
        if value:
            return [item.strip() for item in value.split(",") if item.strip()]
    return [item.strip() for item in default.split(",") if item.strip()]


def env_db_identifier(name, default):
    value = os.environ.get(name, default).strip()
    if not value.replace("_", "").isalnum() or value[0].isdigit():
        raise ValueError(f"{name} must be a simple PostgreSQL identifier.")
    return value


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or 'django-insecure-local-dev-change-me'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = env_list_first(
    ('DJANGO_ALLOWED_HOSTS', 'ALLOWED_HOSTS'),
    'localhost,127.0.0.1,0.0.0.0,control-plane,mlops_paas_django, api.mlops-nids-nt114.id.vn',
)
for host in ('localhost', '127.0.0.1', '0.0.0.0', 'control-plane', 'mlops_paas_django', 'api.mlops-nids-nt114.id.vn'):
    if host not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(host)


# Application definition

INSTALLED_APPS = [
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'corsheaders',
    'storages',
    'channels',
    'authentication',
    'registry',
    'training',
    'drift',
    'monitoring',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'
ASGI_APPLICATION = 'core.asgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DB_SCHEMA = env_db_identifier('DB_SCHEMA', 'control_plane')

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME', 'mlops_paas_db'),
        'USER': os.environ.get('DB_USER', 'postgres'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST_RW', 'postgres'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'OPTIONS': {
            'options': f'-c search_path={DB_SCHEMA},public',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Cấu hình bảo mật JWT (RS256)
from datetime import timedelta
from authentication.tokens.utils import PRIVATE_KEY, PUBLIC_KEY

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=15),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "ALGORITHM": "RS256",
    "SIGNING_KEY": PRIVATE_KEY,
    "VERIFYING_KEY": PUBLIC_KEY,
    "AUDIENCE": "mlops-paas",
    "ISSUER": "django-control-plane",
    "JWK_URL": None,
}

CORS_ALLOWED_ORIGINS = env_list(
    'CORS_ALLOWED_ORIGINS',
    'https://mlops-nids-nt114.id.vn,http://localhost:5173,http://127.0.0.1:5173',
)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cấu hình Custom User Model
AUTH_USER_MODEL = 'authentication.CustomUser'

# Cấu hình Redis Cache (Lưu OTP)
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django Channels - Redis Channel Layer (DB 2, separate from cache DB 1)
_redis_base_url = os.environ.get("REDIS_URL", "redis://127.0.0.1:6379/1")
_channels_redis_url = _redis_base_url.rstrip('/').rsplit('/', 1)[0] + '/2'
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [_channels_redis_url],
            "capacity": 1500,
            "expiry": 60,
        },
    },
}

# Cấu hình gửi tin nhắn (Gmail SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

# Cấu hình Google/GitHub OAuth (Client ID để verify)
GOOGLE_OAUTH2_CLIENT_ID = os.environ.get('GOOGLE_OAUTH2_CLIENT_ID', '')
GITHUB_OAUTH2_CLIENT_ID = os.environ.get('GITHUB_OAUTH2_CLIENT_ID', '')
GITHUB_OAUTH2_CLIENT_SECRET = os.environ.get('GITHUB_OAUTH2_CLIENT_SECRET', '')
GITHUB_OAUTH_REDIRECT_URI = os.environ.get(
    'GITHUB_OAUTH_REDIRECT_URI',
    'http://localhost:5173/oauth/github/callback',
)

MODEL_SERVER_PUBLIC_URL = os.environ.get('MODEL_SERVER_PUBLIC_URL', 'http://localhost:5000')
MODEL_SERVER_INTERNAL_URL = os.environ.get('MODEL_SERVER_INTERNAL_URL', '').rstrip('/')
MODEL_PACKAGER_URL = os.environ.get('MODEL_PACKAGER_URL', 'http://model-packager:7000')
CONTROL_PLANE_INTERNAL_URL = os.environ.get('CONTROL_PLANE_INTERNAL_URL', 'http://control-plane:8000').rstrip('/')
DOCKER_NETWORK_NAME = os.environ.get('DOCKER_NETWORK_NAME', 'mlops_paas_network').strip() or 'mlops_paas_network'
CONTROL_PLANE_WEBHOOK_SECRET = os.environ.get("CONTROL_PLANE_WEBHOOK_SECRET", "super-secret-key").strip()

# Training PaaS configuration (Kubeflow + Local).
TRAINING_BACKEND = os.environ.get('TRAINING_BACKEND', 'local').strip().lower()
LOCAL_TRAINING_TIMEOUT = int(os.environ.get('LOCAL_TRAINING_TIMEOUT', '1800'))
LOCAL_TRAINING_MAX_OUTPUT_MB = int(os.environ.get('LOCAL_TRAINING_MAX_OUTPUT_MB', '500'))
LOCAL_TRAINING_ALLOW_PIP_INSTALL = env_bool('LOCAL_TRAINING_ALLOW_PIP_INSTALL', True)
ENABLE_GPU_TRAINING = env_bool('ENABLE_GPU_TRAINING', False)
TRAINING_MAX_RUNTIME_SECONDS = int(os.environ.get('TRAINING_MAX_RUNTIME_SECONDS', '43200'))
TRAINING_MONTHLY_QUOTA_SECONDS = int(os.environ.get('TRAINING_MONTHLY_QUOTA_SECONDS', '43200'))
TRAINING_MAX_ACTIVE_JOBS_PER_TENANT = int(os.environ.get('TRAINING_MAX_ACTIVE_JOBS_PER_TENANT', '1'))

# Phase 10E.1: MLflow integration settings
# Container/internal URI used when training runs inside docker-compose or local.
MLFLOW_TRACKING_URI = os.environ.get('MLFLOW_TRACKING_URI', 'http://mlflow:5000').strip()
MLFLOW_UI_URL = os.environ.get('MLFLOW_UI_URL', 'http://localhost:5001').rstrip('/')
MLFLOW_EXPERIMENT_NAME = os.environ.get('MLFLOW_EXPERIMENT_NAME', 'mlops-paas-training').strip()
MLFLOW_TRACKING_REQUIRED = env_bool('MLFLOW_TRACKING_REQUIRED', default=False)
MLFLOW_HTTP_REQUEST_TIMEOUT = int(os.environ.get('MLFLOW_HTTP_REQUEST_TIMEOUT', '10') or '10')

# Cấu hình lưu trữ AWS S3 (cho Avatar & File)
# Lưu ý: Không khai báo AWS_ACCESS_KEY_ID và AWS_SECRET_ACCESS_KEY
# boto3 sẽ tự động sử dụng IAM Role được gán cho EC2 instance (cấu hình trong main.tf)
AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_BUCKET_NAME', 'mlops-paas-artifacts')
AWS_S3_REGION_NAME = os.environ.get('AWS_DEFAULT_REGION', 'ap-southeast-1')
AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN') or None

# Tự động gán quyền đọc cho file khi upload lên S3
AWS_DEFAULT_ACL = None
AWS_QUERYSTRING_AUTH = env_bool('AWS_QUERYSTRING_AUTH', True)
# Giữ nguyên tên file, tránh ghi đè ngẫu nhiên quá mức nếu cần
AWS_S3_FILE_OVERWRITE = False
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# Môi trường build trên Docker hoặc Argo
BUILD_STRATEGY = os.environ.get("BUILD_STRATEGY", "docker").lower()

# Harbor Settings
HARBOR_REGISTRY_URL = os.environ.get("HARBOR_REGISTRY_URL", "").strip().rstrip("/")
HARBOR_USER_PROJECT = os.environ.get("HARBOR_USER_PROJECT", "user-images").strip()

# Prometheus Monitoring URL
PROMETHEUS_INTERNAL_URL = os.environ.get("PROMETHEUS_INTERNAL_URL", "").strip().rstrip("/")
