apiVersion: batch/v1
kind: CronJob
metadata:
  name: cleanup-deleted-users
  namespace: default
  labels:
    app: mlops-paas-cronjob
    component: control-plane-cronjob
spec:
  # Chạy vào 00:00 (nửa đêm) mỗi ngày
  schedule: "0 0 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
          - name: django-cleanup
            image: tnvhoang/mlops-paas-django:latest
            imagePullPolicy: Always
            command: ["python", "src/manage.py", "cleanup_users"]
            envFrom:
            - secretRef:
                name: mlops-paas-secret
            - configMapRef:
                name: mlops-paas-control-plane-config
            env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
