apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base/control-plane

images:
- name: mlops-paas-control-plane
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-control-plane
  newTag: 72750ebd637720697d5d47d82e4acabd825d9dfe
