# Cấu hình IngressRoute cho Control Plane (Django Control Plane)
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: control-plane-ingressroute
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`api.mlops-nids-nt114.id.vn`) && (PathPrefix(`/api`) || PathPrefix(`/admin`))
      kind: Rule
      services:
        - name: mlops-paas-control-plane
          port: 8000
