apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

  # GitHub Actions CI/CD pipeline will override this tag with the actual SHA/version dynamically
images:
- name: mlops-paas-consumer
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-consumer
  newTag: cd07f49310d238e0d7697e1105d283622c5eb883
- name: mlops-paas-django
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-django
  newTag: cd07f49310d238e0d7697e1105d283622c5eb883
- name: mlops-paas-web
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-web
  newTag: fe293c42a71b2debf83927a8a756742c34efea42
