apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

  # GitHub Actions CI/CD pipeline will override this tag with the actual SHA/version dynamically
images:
- name: mlops-paas-consumer
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-consumer
  newTag: 375afde3ae576f56733e93b52b2d27fb0faed48d
- name: mlops-paas-control-plane
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-control-plane
  newTag: 7ab6d78280dd916b749cb68a7e6be433f20e2dfe
- name: mlops-paas-model-server
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-model-server
  newTag: 375afde3ae576f56733e93b52b2d27fb0faed48d
- name: mlops-paas-web
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-web
  newTag: 375afde3ae576f56733e93b52b2d27fb0faed48d
