apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- ingress.yaml

  # GitHub Actions CI/CD pipeline will override this tag with the actual SHA/version dynamically
images:
- name: mlops-paas-consumer
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-consumer
  newTag: cec7cac9ecd10dbcec2a51f4a5635f69963ca666
- name: mlops-paas-django
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-django
  newTag: cec7cac9ecd10dbcec2a51f4a5635f69963ca666
- name: mlops-paas-web
  newName: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-web
  newTag: cec7cac9ecd10dbcec2a51f4a5635f69963ca666
