apiVersion: v1
kind: Namespace
metadata:
  name: cloudflare
---
apiVersion: v1
kind: Namespace
metadata:
  name: harbor
---
apiVersion: v1
kind: Namespace
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
---
apiVersion: v1
kind: Namespace
metadata:
  name: user-jobs
