# mlops-nids-sync-data.yaml: Kubernetes Job để chạy script đồng bộ dữ liệu References Data cho PostgreSQL
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mlops-nids-sync-data
  annotations:
    description: "Job to synchronize baseline reference data from S3 to PostgreSQL for data drift detection"
  namespace: default
spec:
  # Số lần Pod được retry lại nếu script bị lỗi trước khi báo Failed toàn bộ Job
  backoffLimit: 2
  template:
    spec:
      nodeSelector:
        workload-type: worker
      restartPolicy: Never
      containers:
        - name: data-sync
          image: tnvhoang/mlops-nids-sync-data:latest # Tên chuẩn theo docker hub username
          imagePullPolicy: Always
          env:
            - name: AWS_DEFAULT_REGION
              value: "ap-southeast-1"
            - name: AWS_BUCKET_NAME
              value: "mlops-nids-artifacts"
            - name: DB_HOST
              value: "mlops-nids-postgres-rw" # Địa chỉ Name Server Cluster IP nội bộ
            - name: DB_NAME
              value: "mlops_nids_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
