# api-servicemonitor.yaml: Cấu hình Prometheus tự động scrape metrics từ FastAPI NIDS API
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nids-api-monitor
  namespace: monitoring
  labels:
    release: monitoring
spec:
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: mlops-nids-api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
