apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Root Kustomization
# Gọi tất cả các module hạ tầng (Infrastructure) và ứng dụng (Apps)
resources:
  # 1. Infrastructure & Platform Services
  - cloudflare
  - postgres
  - redis
  - redpanda
  - secrets
  - storage
  - health
  - monitoring
  - harbor
  - argo-workflows

  # 2. Applications (Dùng overlay production)
  - apps/production
