---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/master
                operator: DoesNotExist
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: aws-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_DEFAULT_REGION
              value: "ap-southeast-1"
            - name: AWS_BUCKET_NAME
              value: "mlops-nids-artifacts"
          args:
            - mlflow
            - server
            - --host
            - "0.0.0.0"
            - --port
            - "5000"
            - --allowed-hosts
            - mlflow.mlops-nids-nt114.id.vn,mlflow.mlops-nids-nt114.id.vn:443,localhost,127.0.0.1,mlflow-service,mlflow-service.default.svc.cluster.local
            - --cors-allowed-origins
            - https://mlflow.mlops-nids-nt114.id.vn
            - --backend-store-uri
            - postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@nids-postgres-rw:5432/mlflow
            - --default-artifact-root
            - s3://$(AWS_BUCKET_NAME)/mlflow-artifacts/
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 2Gi

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
  labels:
    app: mlflow-server
spec:
  type: ClusterIP
  selector:
    app: mlflow-server
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
