# Generated by Django 5.0.3 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_build_metadata"),
        ("registry", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelversion",
            name="source_config_revision",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="modelartifact",
            name="kind",
            field=models.CharField(choices=[("source", "Source"), ("training_output", "Training Output"), ("package", "Package"), ("label_mapping", "Label Mapping"), ("mlflow", "MLflow"), ("image", "Image"), ("metrics", "Metrics"), ("params", "Parameters"), ("model_insights", "Model Insights"), ("feature_importance", "Feature Importance"), ("input_schema", "Input Schema")], max_length=40),
        ),
    ]
