apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mlflow-postgres-secrets-sync
  namespace: mlflow-server
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: postgres-secrets
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: DB_USER
      remoteRef:
        key: mlops/production-secrets
        property: DB_USER
    - secretKey: DB_PASSWORD
      remoteRef:
        key: mlops/production-secrets
        property: DB_PASSWORD
