# Generated by Django 5.0.3 on 2026-05-21 12:50

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.user_avatar_path),
        ),
        migrations.AlterField(
            model_name='useravatar',
            name='image',
            field=models.ImageField(upload_to=authentication.models.user_avatar_history_path),
        ),
    ]
