# Generated by Django 5.0.3 on 2026-06-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_trainingjob_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='max_runtime_seconds',
            field=models.PositiveIntegerField(default=3600),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='memory',
            field=models.PositiveIntegerField(default=4096),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='runtime_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='stop_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='vcpu',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
