# Generated by Django 5.0.3 on 2026-06-19 11:49

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_trainingjob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='label_mapping_file',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.label_mapping_path),
        ),
    ]
