# Generated by Django 5.0.3 on 2026-06-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_trainingjob_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='accelerator_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='accelerator_type',
            field=models.CharField(choices=[('none', 'None'), ('gpu', 'GPU'), ('tpu', 'TPU'), ('trainium', 'Trainium')], default='none', max_length=20),
        ),
    ]
