# Generated by Django 5.0.3 on 2026-06-19 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_trainingjob_accelerator_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingjob',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='authentication.trainingjob'),
        ),
        migrations.AlterField(
            model_name='trainingjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='TrainingJobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=40)),
                ('message', models.CharField(max_length=500)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('training_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='authentication.trainingjob')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['training_job', 'created_at'], name='authenticat_tjevent_4b0b_idx')],
            },
        ),
    ]
