# Generated by Django 5.0.3 on 2026-06-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_modelapi_label_mapping_file'),
        ('authentication', '0015_trainingjob_retry_of_alter_trainingjob_status_and_more'),
    ]

    operations = [
    ]
