# Generated by Django 5.0.3 on 2026-06-20 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_merge_modelapi_trainingjob_heads'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapikey',
            name='allowed_models',
            field=models.ManyToManyField(blank=True, related_name='api_keys', to='authentication.modelapi'),
        ),
        migrations.AddField(
            model_name='userapikey',
            name='scope',
            field=models.CharField(choices=[('all', 'All Models'), ('specific', 'Specific Models')], default='all', max_length=20),
        ),
    ]
