# Generated by Django 5.0.3 on 2026-06-22 03:04

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_userapikey_allowed_models_userapikey_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='reference_data_file',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.model_reference_data_path),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='source_code_file',
            field=models.FileField(blank=True, null=True, upload_to=authentication.models.model_source_code_path),
        ),
    ]
