# Generated by Django 5.0.3 on 2026-06-20 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_modelapi_version_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_container_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_error',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_image_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_internal_path',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_public_path',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='endpoint_status',
            field=models.CharField(choices=[('not_deployed', 'Not Deployed'), ('deploying', 'Deploying'), ('healthy', 'Healthy'), ('unhealthy', 'Unhealthy'), ('deploy_failed', 'Deploy Failed'), ('stopped', 'Stopped')], default='not_deployed', max_length=30),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='status',
            field=models.CharField(choices=[('registered', 'Registered'), ('ready', 'Ready'), ('uploading', 'Uploading'), ('deploying', 'Deploying'), ('deployed', 'Deployed'), ('unhealthy', 'Unhealthy'), ('deploy_failed', 'Deploy Failed'), ('stopped', 'Stopped'), ('archived', 'Archived'), ('error', 'Error'), ('disabled', 'Disabled')], default='ready', max_length=20),
        ),
    ]
