# Generated by Codex on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0017_userapikey_allowed_models_userapikey_scope"),
        ("authentication", "0018_modelapi_endpoint_container_name_and_more"),
    ]

    operations = []
