# Generated by Django 5.0.3 on 2026-06-23 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_modelapi_reference_data_file_and_more'),
        ('authentication', '0019_merge_modelapi_endpoint_userapikey_scope'),
    ]

    operations = [
    ]
