# Generated by Django 5.0.3 on 2026-06-24 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_20260623_0044'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriftMonitoringJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_threshold', models.PositiveIntegerField(default=1000)),
                ('reference_data_s3_path', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_api', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='drift_job', to='authentication.modelapi')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drift_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DriftMonitoringResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_url', models.CharField(blank=True, max_length=1024)),
                ('drift_score', models.FloatField(default=0.0)),
                ('dataset_drift', models.BooleanField(default=False)),
                ('drifted_features_count', models.PositiveIntegerField(default=0)),
                ('total_features', models.PositiveIntegerField(default=0)),
                ('run_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='authentication.driftmonitoringjob')),
            ],
            options={
                'ordering': ['-run_at'],
            },
        ),
    ]
