# Generated by Django 5.0.3 on 2026-06-23 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_merge_20260623_0044'),
        ('authentication', '0022_alter_modeldeploymenthistory_id_alter_modelfamily_id_and_more'),
    ]

    operations = [
    ]
