# Generated by Django 5.0.3 on 2026-06-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0023_merge_20260623_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='mlflow_artifact_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='mlflow_experiment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='mlflow_model_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='modelversion',
            name='mlflow_run_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_artifact_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_experiment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_experiment_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_model_uri',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_run_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_run_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='mlflow_tracking_uri',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
