# Generated by Django 5.0.3 on 2026-06-26 09:38

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0027_modelversion_tracking_summary_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelapi',
            name='artifact',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=authentication.models.model_artifact_path),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='label_mapping_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=authentication.models.label_mapping_path),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='reference_data_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=authentication.models.model_reference_data_path),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='source_artifact',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=authentication.models.model_source_artifact_path),
        ),
        migrations.AlterField(
            model_name='modelapi',
            name='source_code_file',
            field=models.FileField(blank=True, max_length=1024, null=True, upload_to=authentication.models.model_source_code_path),
        ),
    ]
