# Generated by Django 5.0.3 on 2026-06-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_alter_modelapi_artifact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelversion',
            name='model_insights_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='model_insights_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
