# Generated by Django 5.0.3 on 2026-06-27 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_modelversion_model_insights_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='metrics_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='model_insights_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='modelapi',
            name='params_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
