# Generated by Django for Phase 11.1 routing aliases.

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0030_modelapi_metrics_summary_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelRoutingAlias",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("alias_name", models.CharField(max_length=32)),
                ("endpoint_url", models.TextField(blank=True, default="")),
                ("status", models.CharField(default="active", max_length=32)),
                ("promoted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_aliases",
                        to="authentication.modelfamily",
                    ),
                ),
                (
                    "promoted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_model_api",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="routing_alias_targets",
                        to="authentication.modelapi",
                    ),
                ),
                (
                    "target_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="routing_alias_targets",
                        to="authentication.modelversion",
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="model_routing_aliases",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["alias_name"],
                "unique_together": {("tenant", "family", "alias_name")},
            },
        ),
        migrations.AddIndex(
            model_name="modelroutingalias",
            index=models.Index(fields=["tenant", "family", "alias_name"], name="routing_alias_lookup_idx"),
        ),
        migrations.AddIndex(
            model_name="modelroutingalias",
            index=models.Index(fields=["target_version", "status"], name="routing_alias_target_idx"),
        ),
    ]
