# Generated by Django 5.0.3 on 2026-06-29 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_modelroutingalias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingjob',
            name='requirements_file',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='source_zip',
        ),
        migrations.RemoveField(
            model_name='trainingjob',
            name='training_data',
        ),
        migrations.AddField(
            model_name='trainingjob',
            name='model_api',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_jobs', to='authentication.modelapi'),
        ),
    ]
