# Generated by Django 5.0.3 on 2026-07-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0032_remove_trainingjob_requirements_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelapi',
            name='model_type',
            field=models.CharField(
                choices=[('ml', 'Machine Learning'), ('dl', 'Deep Learning')],
                default='ml',
                max_length=10,
            ),
        ),
    ]
