# Generated by Django 5.0.3 on 2026-07-11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0033_modelapi_model_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainingjob",
            name="requirements_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="trainingjob",
            name="training_backend",
            field=models.CharField(
                choices=[("kubeflow", "Kubeflow (Karpenter Autoscaled)"), ("local", "Local")],
                default="kubeflow",
                max_length=20,
            ),
        ),
    ]
