apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-server-config
  namespace: mlflow-server
data:
  AWS_DEFAULT_REGION: "ap-southeast-1"
  MLFLOW_DEFAULT_ARTIFACT_ROOT: "s3://mlops-paas-artifacts/mlflow/"
