expose:
  type: clusterIP
  tls:
    enabled: false
  ingress:
    enabled: false

externalURL: http://harbor.mlops-nids-nt114.id.vn

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      storageClass: ebs-gp3
      size: 5Gi
    jobservice:
      storageClass: ebs-gp3
      size: 1Gi
    redis:
      storageClass: ebs-gp3
      size: 2Gi
    database:
      storageClass: ebs-gp3
      size: 3Gi
  imageChartStorage:
    type: s3
    s3:
      region: ap-southeast-1
      bucket: mlops-paas-harbor-storage

trivy:
  enabled: false
notary:
  enabled: false
