# consumer-deployment.yaml: Triển khai Kafka Consumer để tiêu thụ dữ liệu từ Redpanda và phát hiện Data Drift với Evidently
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-nids-consumer
  annotations:
    description: "Kafka Consumer to process network traffic data in batches and store predictions"
  labels:
    app: mlops-nids-consumer
spec:
  # Consumer chỉ cần 1 replica (dùng kafka group consumer) là đủ để dọn dẹp
  replicas: 1
  selector:
    matchLabels:
      app: mlops-nids-consumer
  template:
    metadata:
      labels:
        app: mlops-nids-consumer
    spec:
      nodeSelector:
        workload-type: worker
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - mlops-nids-consumer
                topologyKey: "kubernetes.io/hostname"
      initContainers:
        - name: init-kafka-topic
          image: docker.redpanda.com/redpandadata/redpanda:v23.3.21
          command: ["/bin/sh", "-c"]
          args: ["rpk topic create nids_production_data --brokers redpanda-service:9092 || true"]
      containers:
        - name: consumer
          # Xài image của API (thư viện confluent-kafka nằm chung)
          image: tnvhoang/mlops-nids-api:92c1790dcb0057200f5eb6272f3e1b590df28dcb
          imagePullPolicy: Always
          command: ["python", "src/consumer.py"]
          # Cấu hình biến môi trường cho Consumer
          env:
            - name: REDPANDA_BROKERS
              value: "redpanda-service:9092"
            - name: EVIDENTLY_TRIGGER_THRESHOLD
              value: "100"
            - name: GITHUB_REPO
              value: "Viet-Hoang-2005/MLOps-nids-system"
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-secrets
                  key: GITHUB_TOKEN
            - name: DB_HOST_RW
              value: "mlops-nids-postgres-rw"
            - name: DB_HOST_RO
              value: "mlops-nids-postgres-ro"
            - name: DB_HOST
              value: "mlops-nids-postgres-rw"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "mlops_nids_db"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_PASSWORD
          # Cấu hình tài nguyên cho Consumer
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
