# dispatch-cronjob.yaml: CronJob kiểm tra định kỳ Model mới trên MLflow
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: mlops-nids-dispatch
  annotations:
    description: "CronJob to poll MLflow for approved Production models and trigger GitHub Actions deployment"
  namespace: default
spec:
  # Chạy mỗi 5 phút
  schedule: "*/5 * * * *"
  # Giữ lại lịch sử của 3 lần chạy thành công và 1 lần thất bại gần nhất
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  # Tránh chạy đè lên nhau nếu job trước đó bị treo
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: mlops-nids-dispatch
        spec:
          nodeSelector:
            workload-type: worker
          restartPolicy: OnFailure
          containers:
            - name: dispatcher
              image: tnvhoang/mlops-nids-dispatch:34302d1e84d4444f1ea689446da94e3f559b374a
              imagePullPolicy: Always
              env:
                # 1. Cấu hình kết nối tới MLflow Server (Nội bộ K3s)
                - name: MLFLOW_TRACKING_URI
                  value: "http://mlflow-service.default.svc.cluster.local:5000"
                - name: MLFLOW_MODEL_NAME
                  value: "NIDS-XGBoost"
                - name: PRODUCTION_ALIAS
                  value: "production"
                - name: MLFLOW_TRACKING_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-credentials
                      key: MLFLOW_TRACKING_USERNAME
                - name: MLFLOW_TRACKING_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: mlflow-credentials
                      key: MLFLOW_TRACKING_PASSWORD
                # 2. Cấu hình kết nối tới GitHub Actions
                - name: GITHUB_REPO
                  value: "Viet-Hoang-2005/MLOps-nids-system"
                - name: GITHUB_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: github-secrets
                      key: GITHUB_TOKEN
              resources:
                requests:
                  cpu: "50m"
                  memory: "64Mi"
                limits:
                  cpu: "100m"
                  memory: "128Mi"
