# Generated by Django 5.0.3 on 2026-07-12 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deployment', '0001_initial'),
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='builds', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='build',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='deployment.build'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deployments', to='registry.modelversion'),
        ),
        migrations.AddField(
            model_name='endpoint',
            name='deployment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endpoint', to='deployment.deployment'),
        ),
        migrations.AddIndex(
            model_name='build',
            index=models.Index(fields=['version', 'status'], name='build_version_status_idx'),
        ),
    ]
