# Generated by Django 5.0.3 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="is_saved",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="build",
            name="saved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
