# Generated by Django 5.1 on 2026-07-15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("deployment", "0003_saved_build")]

    operations = [
        migrations.AddField(
            model_name="build",
            name="discarded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="build",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("queued", "Queued"),
                    ("building", "Building"),
                    ("ready", "Ready"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("discarded", "Discarded"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
    ]
