# Generated by Django 5.0.3 on 2026-07-14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelproject",
            name="model_info",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="modelproject",
            name="next_version_number",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name="ModelBuildMetadata",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("flavor", models.CharField(max_length=80)),
                ("revision", models.PositiveIntegerField(default=1)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="build_metadata", to="catalog.modelproject")),
            ],
        ),
        migrations.CreateModel(
            name="ModelBuildInputAsset",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("kind", models.CharField(choices=[("source_artifact", "Source Artifact"), ("label_mapping", "Label Mapping"), ("metrics", "Metrics"), ("params", "Parameters"), ("model_insights", "Model Insights"), ("feature_importance", "Feature Importance"), ("input_schema", "Input Schema")], max_length=40)),
                ("name", models.CharField(max_length=255)),
                ("s3_uri", models.CharField(max_length=1024)),
                ("checksum", models.CharField(blank=True, max_length=128)),
                ("size_bytes", models.PositiveBigIntegerField(default=0)),
                ("content_type", models.CharField(blank=True, max_length=160)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="build_input_assets", to="catalog.modelproject")),
            ],
        ),
        migrations.AddConstraint(
            model_name="modelbuildinputasset",
            constraint=models.UniqueConstraint(fields=("project", "kind"), name="build_input_project_kind_unique"),
        ),
    ]
