# Generated by Django 5.0.3 on 2026-07-14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_build_metadata"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="modelproject",
            name="model_info",
        ),
    ]
