# Generated by Django 5.0.3 on 2026-07-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_modelproject_model_info"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelbuildmetadata",
            name="artifact_format",
            field=models.CharField(default="raw", max_length=20),
        ),
    ]
