apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-paas-model-server-delete-template
  namespace: default
spec:
  serviceAccountName: argo-workflow-sa
  entrypoint: delete-model
  templates:
    - name: delete-model
      inputs:
        parameters:
          - name: container_name
      steps:
        - - name: deployment
            template: delete-deployment
            arguments:
              parameters:
                - {name: container_name, value: "{{inputs.parameters.container_name}}"}
          - name: service
            template: delete-service
            arguments:
              parameters:
                - {name: container_name, value: "{{inputs.parameters.container_name}}"}

    - name: delete-deployment
      inputs:
        parameters:
          - name: container_name
      resource:
        action: delete
        flags: ["--ignore-not-found"]
        manifest: |
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            name: {{inputs.parameters.container_name}}
            namespace: default

    - name: delete-service
      inputs:
        parameters:
          - name: container_name
      resource:
        action: delete
        flags: ["--ignore-not-found"]
        manifest: |
          apiVersion: v1
          kind: Service
          metadata:
            name: {{inputs.parameters.container_name}}-svc
            namespace: default
