apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-paas-model-server-delete-template
  namespace: default
spec:
  serviceAccountName: argo-workflow-sa
  entrypoint: delete-model
  templates:
    - name: delete-model
      nodeSelector:
        workload-type: worker
      inputs:
        parameters:
          - name: container_name
      script:
        image: bitnami/kubectl:latest
        command: [bash]
        source: |
          set -e
          echo "Deleting resources for container {{inputs.parameters.container_name}}..."
          kubectl delete deployment {{inputs.parameters.container_name}} --ignore-not-found
          kubectl delete service {{inputs.parameters.container_name}}-svc --ignore-not-found
          kubectl delete middleware rewrite-{{inputs.parameters.container_name}} --ignore-not-found
          kubectl delete ingressroute ingressroute-{{inputs.parameters.container_name}} --ignore-not-found
          echo "Successfully deleted resources for {{inputs.parameters.container_name}}"
