apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-eventsource
  namespace: default
spec:
  serviceAccountName: argo-events-sa
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    build:
      port: "12000"
      endpoint: /build
      method: POST
    deploy:
      port: "12000"
      endpoint: /deploy
      method: POST
    drift:
      port: "12000"
      endpoint: /drift
      method: POST
      # Uncomment to restrict to internal cluster calls
      # authSecret:
      #   name: webhook-auth
      #   key: token
