apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-paas-evidently-template
  namespace: default
spec:
  serviceAccountName: argo-workflow-sa
  entrypoint: run-evidently
  templates:
    - name: run-evidently
      inputs:
        parameters:
          - name: job_id
          - name: tenant_id
          - name: model_id
          - name: model_name
          - name: model_uri
          - name: reference_data_url
          - name: html_s3_uri
          - name: report_json_s3_uri
          - name: summary_json_s3_uri
          - name: html_public_url
          - name: html_upload_url
          - name: report_json_upload_url
          - name: summary_json_upload_url
          - name: control_plane_webhook_url
      container:
        image: registry.mlops-nids-nt114.id.vn/mlops-paas/mlops-paas-evidently:08ff1b2cba0150d2df4c60e9f0b4189279b45c1d
        imagePullPolicy: Always
        command: ["python", "/app/detect_drift.py"]
        envFrom:
          - secretRef:
              name: mlops-paas-secret
          - configMapRef:
              name: mlops-paas-control-plane-config
        env:
          - name: JOB_ID
            value: "{{inputs.parameters.job_id}}"
          - name: TENANT_ID
            value: "{{inputs.parameters.tenant_id}}"
          - name: MODEL_ID
            value: "{{inputs.parameters.model_id}}"
          - name: MODEL_NAME
            value: "{{inputs.parameters.model_name}}"
          - name: MODEL_URI
            value: "{{inputs.parameters.model_uri}}"
          - name: REFERENCE_DATA_URL
            value: "{{inputs.parameters.reference_data_url}}"
          - name: DRIFT_THRESHOLD
            value: "0.6"
          - name: HTML_S3_URI
            value: "{{inputs.parameters.html_s3_uri}}"
          - name: REPORT_JSON_S3_URI
            value: "{{inputs.parameters.report_json_s3_uri}}"
          - name: SUMMARY_JSON_S3_URI
            value: "{{inputs.parameters.summary_json_s3_uri}}"
          - name: HTML_PUBLIC_URL
            value: "{{inputs.parameters.html_public_url}}"
          - name: HTML_UPLOAD_URL
            value: "{{inputs.parameters.html_upload_url}}"
          - name: REPORT_JSON_UPLOAD_URL
            value: "{{inputs.parameters.report_json_upload_url}}"
          - name: SUMMARY_JSON_UPLOAD_URL
            value: "{{inputs.parameters.summary_json_upload_url}}"
          - name: CONTROL_PLANE_WEBHOOK_URL
            value: "{{inputs.parameters.control_plane_webhook_url}}"
          - name: DRIFT_REPORTS_S3_PREFIX
            value: "drift-reports"
          - name: DB_HOST_RO
            value: "mlops-paas-postgres-ro"
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi
