apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - rbac.yaml
  - eventbus.yaml
  - eventsource.yaml
  - build-workflowtemplate.yaml
  - deploy-workflowtemplate.yaml
  - evidently-workflowtemplate.yaml
  - sensor.yaml
