apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: mlops-paas-training-cancel-template
  namespace: default
spec:
  serviceAccountName: argo-workflow-sa
  entrypoint: cancel-training
  templates:
    - name: cancel-training
      inputs:
        parameters:
          - name: job_name
          - name: namespace
      resource:
        action: delete
        flags:
          - --ignore-not-found
        manifest: |
          apiVersion: kubeflow.org/v1
          kind: PyTorchJob
          metadata:
            name: {{inputs.parameters.job_name}}
            namespace: {{inputs.parameters.namespace}}
